### ISSUE TITLE
Revisit array type definition

### ISSUE THREAD

**Issue by azeno** [rabbitControl/RCP#11]
The structure should come before the default value or parsing of it is not really possible.

**Comment by i-n-g-o** [comment]
note:
array-data starts with the array-structure, therefore we can always parse the value.

since both default-value and value are optional, we have another option to only specify the array-structure.

tried to clarify this in the specification: 
https://github.com/rabbitControl/RCP/blob/master/RCPValue.md#typedefinition-array

**Comment by i-n-g-o** [comment]
see also: #16
